name: Node.js - Continuous Integration

on:
  workflow_call:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Configure user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: npm
          node-version: 16.14.0
      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit
      - name: Execute format linting
        run: |
          npm run format --if-present
      - name: Execute linting
        run: |
          npm run lint --if-present
      - name: Execute tests
        run: |
          npm run test --if-present
